version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      # Android the primary container
      - image: circleci/android:api-26-ndk-r17b
    environment:
      JVM_OPTS: -Xmx2048m
    steps:
      - checkout
      - run:
          name: list android target
          command: android list target
      # - run:
      #     name: Move into root folder
      #     command: cd AndroidDemo
      - run:
          name: Get Current Directory name
          command: pwd  
          command: ls
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Chmod permissions #if permission for Gradlew Dependencies fail, use this. 
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Setup emulator
          command: sdkmanager "system-images;android-26;default;x86" && echo "no" | avdmanager create avd -n test -k "system-images;android-26;default;x86"
      - run:
          name: Launch emulator
          command: emulator -avd test -netdelay none -netspeed full -no-window -no-audio -gpu off

          background: true
      - run:
          name: Wait emulator
          command: |
            # wait for it to have booted
            circle-android wait-for-boot
            # unlock the emulator screen
            sleep 30
            adb shell input keyevent 82
      - run:
          name: Run EspressoTests
          command: ./gradlew connectedAndroidTest
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/reports/androidTests/connected